# GitHub Action YAML file for triggering auto-training on push in main branch

name: GitHub Actions ML

on:
  push:
    branches: [ main, own_solution ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out development branch
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
          cache: pip

      - name: Install needed Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up DVC for importing necessary data
        uses: iterative/setup-dvc@v1

      - name: Import data from DVC
        run: dvc pull
        
      - name: Run auto-training script
        run: python src/train.py

      - name: Show results in mlflow UI website
        uses: actions/upload-artifact@v2
        with:
          name: mlflow-ui
          path: mlruns
        